export const lang: { [key: string]: string } = {
  search: 'Search',
  searching: 'Searching...',
  searching_w_cancel: 'Searching... (Click to Stop)',
  searching_cont: 'Please wait... (Page will refresh)',
  next_batch: 'Load More...',
  flights: 'Available Flights',
  nonstop: 'Non-Stop',
  first: 'First',
  business: 'Bus',
  premium: 'Prem',
  economy: 'Econ',
  first_full: 'First Class',
  business_full: 'Business Class',
  premium_full: 'Premium Economy',
  economy_full: 'Economy Class',
  date: 'Date',
  error: 'Unknown Error... Try Again',
  bulk_batch: 'Batch Search',
  bulk_flights: 'Flights',
  login: 'Reminder: Login before searching',
  tab_retrieve_fail: 'Failed to retrieve API key. Try logging out and in again.',
  key_exhausted: 'Request quota exhausted, getting a new API key...',
  getting_key: 'Retrieving API key...',
  invalid_airport: 'Invalid Airport',
  invalid_code: 'Invalid Destination Code',
  invalid_date: 'Invalid Date',
  date_too_early: 'Date Too Early',
  date_too_late: 'Date Too Late',
  book_multi: 'Book Multi-City Award',
  search_all_saved: 'Search All Saved'
}
